templates_dir: templates
csv_dir: csv

build:
  pages_dir: pages
  static_dir: static
  output_dir: www

logs:
  logs_dir: apache2
  pattern: "pynw.org-access*"

analytics:
  output_dir: analytics
  base_url: https://pynw.org
